@TestRoslynInNET9_HostAddress = http://localhost:5261

GET {{TestRoslynInNET9_HostAddress}}/todos/
Accept: application/json

###

GET {{TestRoslynInNET9_HostAddress}}/todos/1
Accept: application/json

###
